dist: buster
os: linux
language: python
python: '3.7'
cache:
  directories:
    - $HOME/particl-binaries
stages:
  - lint
env:
script:
  - python setup.py test
after_success:
  - echo "End test"
jobs:
  include:
# lint stage
    - stage: lint
      env:
      cache: false
      language: python
      python: '3.6'
      before_install:
        - sudo apt-get install -y wget gnupg
      install:
        - travis_retry pip install flake8==3.5.0
        - travis_retry pip install codespell==1.15.0
      before_script:
      script:
        - PYTHONWARNINGS="ignore" flake8 --ignore=E501,F841
        - codespell --check-filenames --disable-colors --quiet-level=7 -L keyservers -S .git
      after_success:
        - echo "End lint"
